name: monitor_geral
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  platform: ^3.1.3
  date_utils: ^0.2.0
  flutter_masked_text2: ^0.9.1
  url_launcher: ^6.2.2
  http: ^1.1.2
  material_design_icons_flutter: ^7.0.7296
  #clippy: ^1.0.0
  essential_xlsx: ^2.0.0
  package_info: ^2.0.2
  datetime_picker_formfield_new: ^2.1.0
  shared_preferences: ^2.2.2
  expandable: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

