name: monitor_geral
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  platform: ^3.1.0
  date_utils: ^0.2.0
  flutter_masked_text: ^0.8.0
  url_launcher: ^6.1.3
  http: ^0.13.4
  material_design_icons_flutter: ^4.0.5345
  clippy: ^1.0.0
  essential_xlsx: ^1.1.0
  package_info: ^2.0.2
  datetime_picker_formfield_new: ^2.0.0
  shared_preferences: ^2.0.15
  expandable: ^5.0.1

  flutter:

    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/

